
# HTTP Server
server:
  port: 12342  # HTTP (Tomcat) port


spring:
  application:
<<<<<<< HEAD
    name: ts-login-service

#  zipkin:
#    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
=======
    name: ts-login-service
>>>>>>> 0879857d089cc44ea2b6ea330bd0070ec71a437a
