server:
  port: 18885  # HTTP (Tomcat) port

spring:
  application:
    name: ts-cancel-service
<<<<<<< HEAD
#  zipkin:
#    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
=======
>>>>>>> 0879857d089cc44ea2b6ea330bd0070ec71a437a
