server:
  port: 18673

spring:
  application:
    name: ts-inside-payment-service

  data:
    mongodb:
      host: ts-inside-payment-mongo
#     username: user
#     password: ${MONGODB_PASSWORD}
      database: ts
<<<<<<< HEAD
      port: 27017

#  zipkin:
#    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
=======
      port: 27017
>>>>>>> 0879857d089cc44ea2b6ea330bd0070ec71a437a
